Description: Storage for build artifacts and client packages. Artifacts are removed after 30 days. Client packages are versioned.
Outputs:
  ClientDownloadBucketArn:
    Description: The ARN for the final output bucket of downloadable client packages (not public)
    Value: !Sub "${ClientDownloadBucket.Arn}"
  ArtifactStoreBucketArn:
    Description: The ARN for the encrypted artifact store
    Value: !Sub "${ArtifactStoreBucket.Arn}"
  ClientDownloadBucketName:
    Description: The name for the final output bucket of downloadable client packages (not public)
    Value: !Ref ClientDownloadBucket
  ArtifactStoreBucketName:
    Description: The name for the encrypted artifact store
    Value: !Ref ArtifactStoreBucket

Resources:
  ClientDownloadBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: 'Retain'
    UpdateReplacePolicy: 'Retain'
    Properties:
      VersioningConfiguration:
        Status: Enabled
  
  ArtifactStoreBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: 'Retain'
    UpdateReplacePolicy: 'Retain'
    Properties:
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            ExpirationInDays: 30

  ArtifactStoreBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref ArtifactStoreBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: DenyUnEncryptedObjectUploads
            Effect: Deny
            Principal: '*'
            Action: 's3:PutObject'
            Resource: !Join
              - ''
              - - !GetAtt ArtifactStoreBucket.Arn
                - /*
            Condition:
              StringNotEquals:
                's3:x-amz-server-side-encryption': 'aws:kms'
          - Sid: DenyInsecureConnections
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource: !Join
              - ''
              - - !GetAtt ArtifactStoreBucket.Arn
                - /*
            Condition:
              Bool:
                'aws:SecureTransport': false