version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install --upgrade pip
      - pip install --upgrade awscli
      - apt-get update
      - apt-get -y install ruby-full
      - apt-get -y install jq
      - gem install cfn-nag
  pre_build:
    commands:
      - echo "Template Bucket Package Location is $TEMPLATE_BUCKET"
      - mkdir ${CODEBUILD_SRC_DIR}/package
      - find ${CODEBUILD_SRC_DIR}/templates -name '*.yml' -print0 -or -name '*.yaml' -print0 | xargs -0 -I {file} sh -c 'echo Validating {file}; aws cloudformation validate-template --template-body file://{file}'
      - cfn_nag_scan --input-path ${CODEBUILD_SRC_DIR}/templates/
  build:
    commands:
      - aws cloudformation package --template-file ${CODEBUILD_SRC_DIR}/templates/ops/ue4/main.yml --output-template-file ${CODEBUILD_SRC_DIR}/package/ue4-main.yml --s3-bucket ${TEMPLATE_BUCKET} --s3-prefix ue4-package
      - aws cloudformation package --template-file ${CODEBUILD_SRC_DIR}/templates/bootstrap/main.yml --output-template-file ${CODEBUILD_SRC_DIR}/package/bootstrap-main.yml --s3-bucket ${TEMPLATE_BUCKET} --s3-prefix bs-package
  post_build:
    commands:
      - find ${CODEBUILD_SRC_DIR}/package -name '*.yml' -print0 -or -name '*.yaml' -print0 | xargs -0 -I {file} sh -c 'echo Validating {file}; aws cloudformation validate-template --template-body file://{file}'
      - cfn_nag_scan --input-path ${CODEBUILD_SRC_DIR}/package
artifacts:
  name: TemplateOutput
  files:
    - '**/*'
  discard-paths: yes
  base-directory: 'package'