AWSTemplateFormatVersion: "2010-09-09"
Description: Builds Infrastructure to build and deploy a Unreal Engine 4 container for CI and registers a build for a UE

Parameters:
  GithubOrganization:
    Type: String
    Description: Name of the organization on Github for access
  GithubRepositoryName:
    Type: String
    Description: Name of the repository this lfs configuration.
    Default: main
  BootstrapStackName:
    Type: String
    Description: The stack name containing the exported repo uri for the build image.
    Default: GamePipelinesBootstrap
  CreateGitLfsServerless:
    Type: String
    AllowedValues:
      - Yes
      - No
    Description: Deploy your own Git LFS serverless API for asset heavy projects?
    ConstraintDescription: Yes or No
    Default: Yes
  EngineVersion:
    Type: String
    Description: Version of Unreal Engine 4 to use.
    Default: "4.25.3"
Conditions:
  BuildGitLfsServerless:
    !Equals [ !Ref CreateGitLfsServerless, Yes ]
  NoLfs:
    !Equals [ !Ref CreateGitLfsServerless, No ]
Resources:
  GitLfsServerless:
    Type: AWS::CloudFormation::Stack
    Condition: BuildGitLfsServerless
    Properties:
      TemplateURL: ../core/ops-git-lfs-serverless.yml
      Parameters:
        GithubOrganization: !Ref GithubOrganization
        GithubRepositoryName: !Ref GithubRepositoryName
        GitLfsFunctionBucketName:
          Fn::ImportValue:
            !Sub "${BootstrapStackName}-GitLfsFunctionBucket"
        GitLfsFunctionObjectName:
          Fn::ImportValue:
            !Sub "${BootstrapStackName}-GitLfsFunctionObject"

  Storage:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../../common/ops-storage.yml

  Roles:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ../../common/ops-iam.yml
      Parameters:
        ArtifactStoreBucketArn: !GetAtt Storage.Outputs.ArtifactStoreBucketArn
        ClientDownloadBucketArn: !GetAtt Storage.Outputs.ClientDownloadBucketArn

  BuildProjectWithLfs:
    Type: AWS::CloudFormation::Stack
    Condition: BuildGitLfsServerless
    Properties:
      TemplateURL: ../core/ops-github-build-project.yml
      Parameters:
        BuildRoleArn: !GetAtt Roles.Outputs.CodeBuildRoleArn
        ClientDownloadBucketName: !GetAtt Storage.Outputs.ClientDownloadBucketName
        ProjectEnvironmentType: WINDOWS_SERVER_2019_CONTAINER
        GitHubRepositoryName: !Ref GithubRepositoryName
        GitHubOrganization: !Ref GithubOrganization
        GitLfsUri: !GetAtt GitLfsServerless.Outputs.LfsEndpoint
        ProjectEnvironmentImageName:
          !Join
            - ''
            - - Fn::ImportValue:
                  !Sub "${BootstrapStackName}-Ue4FullRepoUri"
              - "/ue4-full:"
              - !Ref EngineVersion
              - "-ltsc2019"
  BuildProject:
    Type: AWS::CloudFormation::Stack
    Condition: NoLfs
    Properties:
      TemplateURL: ../core/ops-github-build-project.yml
      Parameters:
        BuildRoleArn: !GetAtt Roles.Outputs.CodeBuildRoleArn
        ClientDownloadBucketName: !GetAtt Storage.Outputs.ClientDownloadBucketName
        ProjectEnvironmentType: WINDOWS_SERVER_2019_CONTAINER
        GitHubRepositoryName: !Ref GithubRepositoryName
        GitHubOrganization: !Ref GithubOrganization
        ProjectEnvironmentImageName:
          !Join
            - ''
            - - Fn::ImportValue:
                  !Sub "${BootstrapStackName}-Ue4FullRepoUri"
              - "/ue4-full:"
              - !Ref EngineVersion
              - "-ltsc2019"

Outputs:
  LfsUri:
    Condition: BuildGitLfsServerless
    Description: Uri for git lfs configuration
    Value: !GetAtt GitLfsServerless.Outputs.LfsEndpoint
    Export:
      Name: !Sub "${AWS::StackName}-LfsUri"