Description: Does a ue4-minimal and ue4-full build for UE4 CI use cases. https://docs.adamrehn.com/ue4-docker/use-cases/continuous-integration
Parameters:
  CodeBuildImageEcrArn:
    Type: String
    Description: The ECR to deploy the final build image.
  
  ECRBuildRoleArn:
    Type: String
    Description: Build role that allows access to ECR for pushing.

  ProjectEnvironmentType:
    Type: String
    Description: The type for the project configuration
    AllowedValues:
      - ARM_CONTAINER
      - LINUX_CONTAINER
      - LINUX_GPU_CONTAINER
      - WINDOWS_CONTAINER
      - WINDOWS_SERVER_2019_CONTAINER
    Default: WINDOWS_CONTAINER
      
  ProjectEnvironmentComputeType:
    Type: String
    Description: The compute size type for the project
    AllowedValues:
      - BUILD_GENERAL1_SMALL
      - BUILD_GENERAL1_MEDIUM
      - BUILD_GENERAL1_LARGE
    Default: BUILD_GENERAL1_MEDIUM
      
  ProjectEnvironmentImageName:
    Type: String
    Description: The image to use for the build
    Default: "aws/codebuild/windows-base:2019-1.0"
    
Resources:
  BuildProject:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Name: !Sub '${AWS::StackName}-UE4-ECR-Build'
      Description: !Sub 'Build project for ${AWS::StackName}.'
      ServiceRole: !Ref ECRBuildRoleArn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: !Ref ProjectEnvironmentType
        ComputeType: !Ref ProjectEnvironmentComputeType
        Image: !Ref ProjectEnvironmentImageName
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: true
      TimeoutInMinutes: 60
      Source:
        Type: NO_SOURCE
        BuildSpec: >
          version: 0.2
          env:
            variables:
              UE4_ENGINE_VERSION: "4.25.4"
          phases:
            runtime-versions:
              - python: 3.8.3
            install:
              commands:
                - ue4-docker build %UE4_ENGINE_VERSION% --no-engine --no-full
            pre_build:
              commands:
                - ue4-docker build %UE4_ENGINE_VERSION% --no-engine --no-full
                - ue4-docker clean --source
            build:
              commands:
                - 
            post_build:
              commands:
                - echo Uploading image to ECR on `date`
