version: 0.2
phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - 'export IMAGE_TAG="$MAJOR_MINOR_VERSION.$CODEBUILD_BUILD_NUMBER"'
  build:
    commands:
      - docker build -t $DOCKER_PROJECT:$IMAGE_TAG $CODEBUILD_SRC_DIR/dockerfiles/$DOCKER_PROJECT
      - docker tag $DOCKER_PROJECT:$IMAGE_TAG $DOCKER_REPOSITORY:$IMAGE_TAG
  post_build:
    commands:
      - docker push $DOCKER_REPOSITORY:$IMAGE_TAG