AWSTemplateFormatVersion: 2010-09-09
Description: Defines Default IAM roles if you allow the CloudFormation Template to create IAM roles for you.
Resources:
  CodeBuildECR:
    Type: AWS::ECR::Repository
    DeletionPolicy: 'Retain'
    UpdateReplacePolicy: 'Retain'
    Properties: 
      ImageTagMutability: IMMUTABLE
      RepositoryName: 'ops-images'
      RepositoryPolicyText: 
        Version: "2012-10-17"
        Statement: 
          - Sid: AllowPushPull
            Effect: Allow
            Principal: 
              Service:
                - codedeploy.amazonaws.com
                - codepipeline.amazonaws.com
                - codebuild.amazonaws.com
                - ec2.amazonaws.com #TODO: this should be more fine grained, needed to support the fat container builder
            Action: 
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:PutImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"
Outputs:
  RepositoryName:
    Description: The name of the repository
    Value: !Ref CodeBuildECR
  RepositoryArn:
    Description: The ARN of the repository
    Value: !GetAtt CodeBuildECR.Arn
