AWSTemplateFormatVersion: 2010-09-09
Description: Storage for build artifacts and client packages. Artifacts are removed after 30 days. Client packages are versioned.
Outputs:
  ClientDownloadBucketArn:
    Description: The ARN for the final output bucket of downloadable client packages (not public)
    Value: !GetAtt ClientDownloadBucket.Arn
  ArtifactStoreBucketArn:
    Description: The ARN for the encrypted artifact store
    Value: !GetAtt ArtifactStoreBucket.Arn
  ClientDownloadBucketName:
    Description: The name for the final output bucket of downloadable client packages (not public)
    Value: !Ref ClientDownloadBucket
  ArtifactStoreBucketName:
    Description: The name for the encrypted artifact store
    Value: !Ref ArtifactStoreBucket

Resources:
  ClientDownloadBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: 'Retain'
    UpdateReplacePolicy: 'Retain'
    Properties:
      VersioningConfiguration:
        Status: Enabled
  
  ArtifactStoreBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: 'Retain'
    UpdateReplacePolicy: 'Retain'
    Properties:
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            ExpirationInDays: 30
      VersioningConfiguration:
        Status: Enabled

  ArtifactStoreBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref ArtifactStoreBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: DenyNonPipelineMutations
            Effect: Deny
            Action:
              - 's3:PutObject'
              - 's3:PutObjectAcl'
              - 's3:DeleteObject'
              - 's3:DeleteObjectVersion'
              - 's3:DeleteObjectVersionTagging'
              - 's3:DeleteBucket'
            Resource: !Join
              - ''
              - - !GetAtt ArtifactStoreBucket.Arn
                - /*
            NotPrincipal:
              Service:
                - codebuild.amazonaws.com
                - codepipeline.amazonaws.com
                - codedeploy.amazonaws.com
          - Sid: DenyUnEncryptedObjectUploads
            Effect: Deny
            Principal: '*'
            Action: 's3:PutObject'
            Resource: !Join
              - ''
              - - !GetAtt ArtifactStoreBucket.Arn
                - /*
            Condition:
              StringNotEquals:
                's3:x-amz-server-side-encryption': 'aws:kms'
          - Sid: DenyInsecureConnections
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource: !Join
              - ''
              - - !GetAtt ArtifactStoreBucket.Arn
                - /*
            Condition:
              Bool:
                'aws:SecureTransport': false