AWSTemplateFormatVersion: 2010-09-09
Description: Defines Default IAM roles if you allow the CloudFormation Template to create IAM roles for you.
Parameters:
  RepositoryName:
    Type: String
    Description: The name of the repository. Will be scoped to /ops/
Resources:
  CodeBuildECR:
    Type: AWS::ECR::Repository
    DeletionPolicy: 'Retain'
    UpdateReplacePolicy: 'Retain'
    Properties: 
      ImageTagMutability: IMMUTABLE
      RepositoryName: !Sub "ops/${RepositoryName}"
      RepositoryPolicyText: 
        Version: "2012-10-17"
        Statement: 
          - Sid: AllowServicesPushPull
            Effect: Allow
            Principal:
              Service:
                - codedeploy.amazonaws.com
                - codepipeline.amazonaws.com
                - codebuild.amazonaws.com
                - ec2.amazonaws.com
            Action: 
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:PutImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"
Outputs:
  RepositoryName:
    Description: The name of the repository
    Value: !Ref CodeBuildECR
  RepositoryArn:
    Description: The ARN of the repository
    Value: !GetAtt CodeBuildECR.Arn
  RepositoryURI:
    Description: The full URI to the repository
    Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${CodeBuildECR}"

