AWSTemplateFormatVersion: 2010-09-09
Description: Defines Default IAM roles if you allow the CloudFormation Template to create IAM roles for you.
Resources:
  CodeBuildECR:
    Type: AWS::ECR::Repository
    DeletionPolicy: 'Retain'
    UpdateReplacePolicy: 'Retain'
    Properties: 
      ImageTagMutability: IMMUTABLE
      RepositoryName: 'codebuild-images'
      RepositoryPolicyText: 
        Version: "2012-10-17"
        Statement: 
          - Sid: AllowPushPull
            Effect: Allow
            Principal: 
              Service:
                - codedeploy.amazonaws.com
                - codepipeline.amazonaws.com
                - codebuild.amazonaws.com
            Action: 
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:PutImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"
          